export default [
  {
    "id": "gear-paratus",
    "name": "Gear Paratus",
    "brand": "3V",
    "model": "Gear Paratus",
    "volume": 30,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "3V Gear",
    "openingStyle": "Top-loading"
  },
  {
    "id": "gear-velox-ii",
    "name": "Gear Velox II",
    "brand": "3V",
    "model": "Gear Velox II",
    "volume": 25,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "3V Gear",
    "openingStyle": "Top-loading"
  },
  {
    "id": "carry-daily",
    "name": "Carry Daily",
    "brand": "Able",
    "model": "Carry Daily",
    "volume": 21,
    "weight": 1.1,
    "dimensions": "45 x 28 x 15",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Able Carry",
    "openingStyle": "Clamshell"
  },
  {
    "id": "carry-max",
    "name": "Carry Max",
    "brand": "Able",
    "model": "Carry Max",
    "volume": 30,
    "weight": 1.4,
    "dimensions": "50 x 30 x 20",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Able Carry",
    "openingStyle": "Clamshell"
  },
  {
    "id": "city-pack-pro",
    "name": "City Pack Pro",
    "brand": "Aer",
    "model": "City Pack Pro",
    "volume": 24,
    "weight": 1.2,
    "dimensions": "46 x 30 x 16",
    "price": 220,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Clamshell"
  },
  {
    "id": "flight-pack-3",
    "name": "Flight Pack 3",
    "brand": "Aer",
    "model": "Flight Pack 3",
    "volume": 20,
    "weight": 1.1,
    "dimensions": "45 x 28 x 15",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Clamshell"
  },
  {
    "id": "travel-pack-3-small",
    "name": "Travel Pack 3 Small",
    "brand": "Aer",
    "model": "Travel Pack 3 Small",
    "volume": 28,
    "weight": 1.4,
    "dimensions": "48 x 30 x 18",
    "price": 230,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Clamshell"
  },
  {
    "id": "travel-pack-3-x-pac",
    "name": "Travel Pack 3 X-Pac",
    "brand": "Aer",
    "model": "Travel Pack 3 X-Pac",
    "volume": 35,
    "weight": 1.5,
    "dimensions": "55 x 35 x 20",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Aer",
    "openingStyle": "Clamshell"
  },
  {
    "id": "equipment-30l-zip-access",
    "name": "Equipment 30L Zip Access",
    "brand": "Alchemy",
    "model": "Equipment 30L Zip Access",
    "volume": 30,
    "weight": 1.2,
    "dimensions": "50 x 32 x 18",
    "price": 280,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Alchemy Equipment",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "equipment-35l-roll-top",
    "name": "Equipment 35L Roll Top",
    "brand": "Alchemy",
    "model": "Equipment 35L Roll Top",
    "volume": 35,
    "weight": 1.4,
    "dimensions": "54 x 32 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Alchemy Equipment",
    "openingStyle": "Roll-top"
  },
  {
    "id": "oak-backpack",
    "name": "Oak Backpack",
    "brand": "Almond",
    "model": "Oak Backpack",
    "volume": 25,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Almond Oak",
    "openingStyle": "Top-loading"
  },
  {
    "id": "elements-backpack-pro",
    "name": "Elements Backpack Pro",
    "brand": "Alpaka",
    "model": "Elements Backpack Pro",
    "volume": 25,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Alpaka",
    "openingStyle": "Clamshell"
  },
  {
    "id": "go-sling-pro",
    "name": "Go Sling Pro",
    "brand": "Alpaka",
    "model": "Go Sling Pro",
    "volume": 10,
    "weight": 0.5,
    "dimensions": "35 x 20 x 10",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Alpaka",
    "openingStyle": "Top-loading"
  },
  {
    "id": "eagle-creek-tour-travel-pack-40l",
    "name": "Tour Travel Pack 40L",
    "brand": "Eagle Creek",
    "model": "Tour Travel Pack 40L",
    "volume": 40,
    "weight": 1.3,
    "dimensions": "52 x 33 x 23",
    "price": 170,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Clamshell"
  },
  {
    "id": "evergoods-ctb35",
    "name": "CIVIC Travel Bag 35L",
    "brand": "Evergoods",
    "model": "CIVIC Travel Bag 35L",
    "volume": 35,
    "weight": 1.8,
    "dimensions": "52 x 30.5 x 24",
    "price": 349,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes (17\")",
    "waterBottleCompartment": "Yes",
    "source": "Evergoods",
    "openingStyle": "Clamshell"
  },
  {
    "id": "granville-16",
    "name": "Granville 16",
    "brand": "Arcteryx",
    "model": "Granville 16",
    "volume": 16,
    "weight": 0.6,
    "dimensions": "45 x 28 x 15",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "granville-25",
    "name": "Granville 25",
    "brand": "Arcteryx",
    "model": "Granville 25",
    "volume": 25,
    "weight": 0.8,
    "dimensions": "48 x 30 x 18",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "gear-24l",
    "name": "Gear 24L",
    "brand": "Axiom",
    "model": "Gear 24L",
    "volume": 24,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Axiom Gear",
    "openingStyle": "Top-loading"
  },
  {
    "id": "gear-36l",
    "name": "Gear 36L",
    "brand": "Axiom",
    "model": "Gear 36L",
    "volume": 36,
    "weight": 1.3,
    "dimensions": "55 x 35 x 20",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Axiom Gear",
    "openingStyle": "Top-loading"
  },
  {
    "id": "apex-backpack",
    "name": "Apex Backpack",
    "brand": "Bellroy",
    "model": "Apex Backpack",
    "volume": 25,
    "weight": 1.2,
    "dimensions": "48 x 30 x 18",
    "price": 349,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "classic-backpack-plus",
    "name": "Classic Backpack Plus",
    "brand": "Bellroy",
    "model": "Classic Backpack Plus",
    "volume": 20,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Top-loading"
  },
  {
    "id": "lite-daypack",
    "name": "Lite Daypack",
    "brand": "Bellroy",
    "model": "Lite Daypack",
    "volume": 16,
    "weight": 0.4,
    "dimensions": "40 x 25 x 12",
    "price": 99,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "lite-travel-backpack-30l",
    "name": "Lite Travel Backpack 30L",
    "brand": "Bellroy",
    "model": "Lite Travel Backpack 30L",
    "volume": 30,
    "weight": 0.950,
    "dimensions": "50 x 30 x 20",
    "price": 229,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "lite-travel-backpack-38l",
    "name": "Lite Travel Backpack 38L",
    "brand": "Bellroy",
    "model": "Lite Travel Backpack 38L",
    "volume": 38,
    "weight": 1,
    "dimensions": "55 x 35 x 20",
    "price": 279,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "studio-backpack",
    "name": "Studio Backpack",
    "brand": "Bellroy",
    "model": "Studio Backpack",
    "volume": 18,
    "weight": 0.75,
    "dimensions": "42 x 26 x 14",
    "price": 199,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "tokyo-totepack",
    "name": "Tokyo Totepack",
    "brand": "Bellroy",
    "model": "Tokyo Totepack",
    "volume": 20,
    "weight": 0.7,
    "dimensions": "45 x 28 x 15",
    "price": 179,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Tote"
  },
  {
    "id": "transit-backpack",
    "name": "Transit Backpack",
    "brand": "Bellroy",
    "model": "Transit Backpack",
    "volume": 28,
    "weight": 1.2,
    "dimensions": "48 x 30 x 18",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Clamshell"
  },
  {
    "id": "transit-backpack-28l",
    "name": "Transit Backpack 28L",
    "brand": "Bellroy",
    "model": "Transit Backpack 28L",
    "volume": 28,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 249,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Clamshell"
  },
  {
    "id": "transit-backpack-plus",
    "name": "Transit Backpack Plus",
    "brand": "Bellroy",
    "model": "Transit Backpack Plus",
    "volume": 38,
    "weight": 1.4,
    "dimensions": "55 x 35 x 20",
    "price": 299,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Clamshell"
  },
  {
    "id": "transit-duffel",
    "name": "Transit Duffel",
    "brand": "Bellroy",
    "model": "Transit Duffel",
    "volume": 40,
    "weight": 1.4,
    "dimensions": "60 x 35 x 20",
    "price": 299,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Duffel"
  },
  {
    "id": "transit-duffel-40l",
    "name": "Transit Duffel 40L",
    "brand": "Bellroy",
    "model": "Transit Duffel 40L",
    "volume": 40,
    "weight": 1.4,
    "dimensions": "60 x 35 x 20",
    "price": 299,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Duffel"
  },
  {
    "id": "transit-duffel-60l",
    "name": "Transit Duffel 60L",
    "brand": "Bellroy",
    "model": "Transit Duffel 60L",
    "volume": 60,
    "weight": 1.8,
    "dimensions": "65 x 35 x 25",
    "price": 349,
    "carryOnLegal": "No",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Duffel"
  },
  {
    "id": "transit-workpack",
    "name": "Transit Workpack",
    "brand": "Bellroy",
    "model": "Transit Workpack",
    "volume": 20,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 229,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "transit-workpack-20l",
    "name": "Transit Workpack 20L",
    "brand": "Bellroy",
    "model": "Transit Workpack 20L",
    "volume": 20,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 229,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "venture-backpack",
    "name": "Venture Backpack",
    "brand": "Bellroy",
    "model": "Venture Backpack",
    "volume": 22,
    "weight": 0.85,
    "dimensions": "46 x 28 x 16",
    "price": 199,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "weekender",
    "name": "Weekender",
    "brand": "Bellroy",
    "model": "Weekender",
    "volume": 35,
    "weight": 1.3,
    "dimensions": "55 x 35 x 20",
    "price": 249,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Duffel"
  },
  {
    "id": "weekender-35l",
    "name": "Weekender 35L",
    "brand": "Bellroy",
    "model": "Weekender 35L",
    "volume": 35,
    "weight": 1.3,
    "dimensions": "55 x 35 x 20",
    "price": 249,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Duffel"
  },
  {
    "id": "weekender-plus",
    "name": "Weekender Plus",
    "brand": "Bellroy",
    "model": "Weekender Plus",
    "volume": 45,
    "weight": 1.5,
    "dimensions": "60 x 35 x 20",
    "price": 299,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Bellroy",
    "openingStyle": "Duffel"
  },
  {
    "id": "diamond-creek-20",
    "name": "Diamond Creek 20",
    "brand": "Black",
    "model": "Diamond Creek 20",
    "volume": 20,
    "weight": 0.7,
    "dimensions": "45 x 28 x 15",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Black Diamond",
    "openingStyle": "Top-loading"
  },
  {
    "id": "diamond-stonehauler-30",
    "name": "Diamond Stonehauler 30",
    "brand": "Black",
    "model": "Diamond Stonehauler 30",
    "volume": 30,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 160,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "diamond-stonehauler-45",
    "name": "Diamond Stonehauler 45",
    "brand": "Black",
    "model": "Diamond Stonehauler 45",
    "volume": 45,
    "weight": 1.3,
    "dimensions": "55 x 35 x 23",
    "price": 180,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "ember-citadel-r2",
    "name": "Ember Citadel R2",
    "brand": "Black",
    "model": "Ember Citadel R2",
    "volume": 25,
    "weight": 1.3,
    "dimensions": "48 x 30 x 18",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Black Ember",
    "openingStyle": "Clamshell"
  },
  {
    "id": "ember-forge-max",
    "name": "Ember Forge Max",
    "brand": "Black",
    "model": "Ember Forge Max",
    "volume": 30,
    "weight": 1.5,
    "dimensions": "50 x 30 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Black Ember",
    "openingStyle": "Clamshell"
  },
  {
    "id": "supply-errant-pack",
    "name": "Supply Errant Pack",
    "brand": "Boundary",
    "model": "Supply Errant Pack",
    "volume": 24,
    "weight": 1.2,
    "dimensions": "45 x 28 x 15",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Boundary Supply",
    "openingStyle": "Clamshell"
  },
  {
    "id": "supply-prima-system",
    "name": "Supply Prima System",
    "brand": "Boundary",
    "model": "Supply Prima System",
    "volume": 30,
    "weight": 1.6,
    "dimensions": "50 x 30 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Boundary Supply",
    "openingStyle": "Clamshell"
  },
  {
    "id": "classic-36l",
    "name": "Classic 36L",
    "brand": "CabinZero",
    "model": "Classic 36L",
    "volume": 36,
    "weight": 0.8,
    "dimensions": "55 x 35 x 20",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "CabinZero",
    "openingStyle": "Clamshell"
  },
  {
    "id": "military-28l",
    "name": "Military 28L",
    "brand": "CabinZero",
    "model": "Military 28L",
    "volume": 28,
    "weight": 0.7,
    "dimensions": "48 x 30 x 18",
    "price": 90,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "CabinZero",
    "openingStyle": "Clamshell"
  },
  {
    "id": "industries-barrage-cargo",
    "name": "Industries Barrage Cargo",
    "brand": "Chrome",
    "model": "Industries Barrage Cargo",
    "volume": 32,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "industries-urban-ex-20l",
    "name": "Industries Urban Ex 20L",
    "brand": "Chrome",
    "model": "Industries Urban Ex 20L",
    "volume": 20,
    "weight": 0.7,
    "dimensions": "43 x 25 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "industries-vega-25",
    "name": "Industries Vega 25",
    "brand": "Chrome",
    "model": "Industries Vega 25",
    "volume": 25,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Chrome Industries",
    "openingStyle": "Roll-top"
  },
  {
    "id": "isar-large",
    "name": "Isar Large",
    "brand": "Côte&Ciel",
    "model": "Isar Large",
    "volume": 28,
    "weight": 1.2,
    "dimensions": "48 x 30 x 18",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "No",
    "source": "Côte&Ciel",
    "openingStyle": "Top-loading"
  },
  {
    "id": "nile",
    "name": "Nile",
    "brand": "Côte&Ciel",
    "model": "Nile",
    "volume": 20,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "No",
    "source": "Côte&Ciel",
    "openingStyle": "Top-loading"
  },
  {
    "id": "allpa-28l",
    "name": "Allpa 28L",
    "brand": "Cotopaxi",
    "model": "Allpa 28L",
    "volume": 28,
    "weight": 1.2,
    "dimensions": "48 x 30 x 18",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Clamshell"
  },
  {
    "id": "allpa-42l",
    "name": "Allpa 42L",
    "brand": "Cotopaxi",
    "model": "Allpa 42L",
    "volume": 42,
    "weight": 1.7,
    "dimensions": "55 x 35 x 23",
    "price": 220,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Clamshell"
  },
  {
    "id": "batac-24l",
    "name": "Batac 24L",
    "brand": "Cotopaxi",
    "model": "Batac 24L",
    "volume": 24,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "dover-dakota-backpack",
    "name": "Dover Dakota Backpack",
    "brand": "Dagne",
    "model": "Dover Dakota Backpack",
    "volume": 25,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Dagne Dover",
    "openingStyle": "Clamshell"
  },
  {
    "id": "dover-landon-carryall",
    "name": "Dover Landon Carryall",
    "brand": "Dagne",
    "model": "Dover Landon Carryall",
    "volume": 30,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Dagne Dover",
    "openingStyle": "Clamshell"
  },
  {
    "id": "bags-recon",
    "name": "Bags Recon",
    "brand": "Defy",
    "model": "Bags Recon",
    "volume": 22,
    "weight": 0.8,
    "dimensions": "43 x 25 x 15",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "giga-28",
    "name": "Giga 28",
    "brand": "Deuter",
    "model": "Giga 28",
    "volume": 28,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "transit-50",
    "name": "Transit 50",
    "brand": "Deuter",
    "model": "Transit 50",
    "volume": 50,
    "weight": 1.4,
    "dimensions": "60 x 35 x 25",
    "price": 150,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "ruckpack",
    "name": "Ruckpack",
    "brand": "DSPTCH",
    "model": "Ruckpack",
    "volume": 25,
    "weight": 1.2,
    "dimensions": "48 x 30 x 18",
    "price": 240,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "DSPTCH",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "creek-global-companion-40l",
    "name": "Creek Global Companion 40L",
    "brand": "Eagle",
    "model": "Creek Global Companion 40L",
    "volume": 40,
    "weight": 1.3,
    "dimensions": "55 x 35 x 20",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "creek-tour-travel-pack-40l",
    "name": "Creek Tour Travel Pack 40L",
    "brand": "Eagle",
    "model": "Creek Tour Travel Pack 40L",
    "volume": 40,
    "weight": 1.2,
    "dimensions": "55 x 35 x 20",
    "price": 160,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "out-of-office",
    "name": "Out Of Office",
    "brand": "Eastpak",
    "model": "Out Of Office",
    "volume": 30,
    "weight": 0.8,
    "dimensions": "50 x 30 x 20",
    "price": 80,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Eastpak",
    "openingStyle": "Top-loading"
  },
  {
    "id": "padded-pak-r",
    "name": "Padded Pak'r",
    "brand": "Eastpak",
    "model": "Padded Pak'r",
    "volume": 25,
    "weight": 0.5,
    "dimensions": "45 x 28 x 15",
    "price": 50,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Eastpak",
    "openingStyle": "Top-loading"
  },
  {
    "id": "professional-weekender",
    "name": "Professional Weekender",
    "brand": "eBags",
    "model": "Professional Weekender",
    "volume": 30,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "eBags",
    "openingStyle": "Clamshell"
  },
  {
    "id": "tls-mother-lode-weekender",
    "name": "TLS Mother Lode Weekender",
    "brand": "eBags",
    "model": "TLS Mother Lode Weekender",
    "volume": 35,
    "weight": 1.4,
    "dimensions": "55 x 35 x 20",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "eBags",
    "openingStyle": "Clamshell"
  },
  {
    "id": "chz22",
    "name": "CHZ22",
    "brand": "Evergoods",
    "model": "CHZ22",
    "volume": 22,
    "weight": 1.1,
    "dimensions": "45 x 28 x 15",
    "price": 229,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "chz26",
    "name": "CHZ26",
    "brand": "Evergoods",
    "model": "CHZ26",
    "volume": 26,
    "weight": 1.2,
    "dimensions": "48 x 30 x 18",
    "price": 249,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "cpl24",
    "name": "CPL24",
    "brand": "Evergoods",
    "model": "CPL24",
    "volume": 24,
    "weight": 1.1,
    "dimensions": "45 x 28 x 15",
    "price": 289,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "kanken-17",
    "name": "Fjallraven Kanken 17",
    "brand": "Fjallraven",
    "model": "Kanken 17",
    "volume": 17,
    "weight": 0.3,
    "dimensions": "40 x 25 x 13",
    "price": 80,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "No",
    "source": "Fjällräven",
    "openingStyle": "Top-loading"
  },
  {
    "id": "kanken-20",
    "name": "Fjallraven Kanken 20",
    "brand": "Fjallraven",
    "model": "Kanken 20",
    "volume": 20,
    "weight": 0.4,
    "dimensions": "43 x 28 x 15",
    "price": 90,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "raven-28",
    "name": "Fjallraven Raven 28",
    "brand": "Fjallraven",
    "model": "Raven 28",
    "volume": 28,
    "weight": 1.1,
    "dimensions": "48 x 30 x 18",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "gr1-21l",
    "name": "GR1 21L",
    "brand": "Goruck",
    "model": "GR1 21L",
    "volume": 21,
    "weight": 1.3,
    "dimensions": "45 x 28 x 15",
    "price": 295,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "gr1-26l",
    "name": "GR1 26L",
    "brand": "Goruck",
    "model": "GR1 26L",
    "volume": 26,
    "weight": 1.5,
    "dimensions": "48 x 30 x 18",
    "price": 295,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "gr2-40l",
    "name": "GR2 40L",
    "brand": "Goruck",
    "model": "GR2 40L",
    "volume": 40,
    "weight": 2,
    "dimensions": "55 x 35 x 20",
    "price": 395,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "explorer-mini",
    "name": "Explorer Mini",
    "brand": "Gravel",
    "model": "Explorer Mini",
    "volume": 20,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Gravel",
    "openingStyle": "Clamshell"
  },
  {
    "id": "explorer-plus",
    "name": "Explorer Plus",
    "brand": "Gravel",
    "model": "Explorer Plus",
    "volume": 30,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Gravel",
    "openingStyle": "Clamshell"
  },
  {
    "id": "rainmaker",
    "name": "Rainmaker",
    "brand": "Greenroom136",
    "model": "Rainmaker",
    "volume": 25,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "border-25",
    "name": "Border 25",
    "brand": "Gregory",
    "model": "Border 25",
    "volume": 25,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "border-35",
    "name": "Border 35",
    "brand": "Gregory",
    "model": "Border 35",
    "volume": 35,
    "weight": 1.3,
    "dimensions": "53 x 33 x 20",
    "price": 140,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "nano-22",
    "name": "Nano 22",
    "brand": "Gregory",
    "model": "Nano 22",
    "volume": 22,
    "weight": 0.8,
    "dimensions": "45 x 28 x 15",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Gregory",
    "openingStyle": "Top-loading"
  },
  {
    "id": "tight-pro-large",
    "name": "Tight Pro Large",
    "brand": "Haglöfs",
    "model": "Tight Pro Large",
    "volume": 30,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 160,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Haglöfs",
    "openingStyle": "Top-loading"
  },
  {
    "id": "vide-medium",
    "name": "Vide Medium",
    "brand": "Haglöfs",
    "model": "Vide Medium",
    "volume": 20,
    "weight": 0.8,
    "dimensions": "45 x 28 x 15",
    "price": 130,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Haglöfs",
    "openingStyle": "Top-loading"
  },
  {
    "id": "monolith-daypack",
    "name": "Monolith Daypack",
    "brand": "Heimplanet",
    "model": "Monolith Daypack",
    "volume": 22,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Heimplanet",
    "openingStyle": "Clamshell"
  },
  {
    "id": "transit-line-travel-pack",
    "name": "Transit Line Travel Pack",
    "brand": "Heimplanet",
    "model": "Transit Line Travel Pack",
    "volume": 34,
    "weight": 1.5,
    "dimensions": "50 x 30 x 20",
    "price": 280,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Heimplanet",
    "openingStyle": "Clamshell"
  },
  {
    "id": "little-america",
    "name": "Little America",
    "brand": "Herschel",
    "model": "Little America",
    "volume": 25,
    "weight": 0.7,
    "dimensions": "45 x 28 x 15",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "settlement",
    "name": "Settlement",
    "brand": "Herschel",
    "model": "Settlement",
    "volume": 22,
    "weight": 0.6,
    "dimensions": "43 x 25 x 15",
    "price": 80,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "eo-travel-backpack",
    "name": "EO Travel Backpack",
    "brand": "Incase",
    "model": "EO Travel Backpack",
    "volume": 30,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Incase",
    "openingStyle": "Clamshell"
  },
  {
    "id": "icon-backpack",
    "name": "Icon Backpack",
    "brand": "Incase",
    "model": "Icon Backpack",
    "volume": 25,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Incase",
    "openingStyle": "Clamshell"
  },
  {
    "id": "wolfskin-berkeley",
    "name": "Wolfskin Berkeley",
    "brand": "Jack",
    "model": "Wolfskin Berkeley",
    "volume": 25,
    "weight": 0.6,
    "dimensions": "47 x 29 x 17",
    "price": 80,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Jack Wolfskin",
    "openingStyle": "Top-loading"
  },
  {
    "id": "wolfskin-trt-32-pack",
    "name": "Wolfskin TRT 32 Pack",
    "brand": "Jack",
    "model": "Wolfskin TRT 32 Pack",
    "volume": 32,
    "weight": 1.3,
    "dimensions": "50 x 30 x 20",
    "price": 140,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Jack Wolfskin",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "right-pack",
    "name": "Right Pack",
    "brand": "JanSport",
    "model": "Right Pack",
    "volume": 31,
    "weight": 0.5,
    "dimensions": "48 x 30 x 18",
    "price": 50,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "superbreak",
    "name": "SuperBreak",
    "brand": "JanSport",
    "model": "SuperBreak",
    "volume": 25,
    "weight": 0.4,
    "dimensions": "45 x 28 x 15",
    "price": 40,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "asher-25",
    "name": "Asher 25",
    "brand": "Kelty",
    "model": "Asher 25",
    "volume": 25,
    "weight": 0.9,
    "dimensions": "48 x 30 x 18",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Kelty",
    "openingStyle": "Top-loading"
  },
  {
    "id": "asher-35",
    "name": "Asher 35",
    "brand": "Kelty",
    "model": "Asher 35",
    "volume": 35,
    "weight": 1.1,
    "dimensions": "55 x 35 x 20",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Kelty",
    "openingStyle": "Top-loading"
  },
  {
    "id": "asher-45",
    "name": "Asher 45",
    "brand": "Kelty",
    "model": "Asher 45",
    "volume": 45,
    "weight": 1.3,
    "dimensions": "60 x 35 x 25",
    "price": 140,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Kelty",
    "openingStyle": "Top-loading"
  },
  {
    "id": "asher-55",
    "name": "Asher 55",
    "brand": "Kelty",
    "model": "Asher 55",
    "volume": 55,
    "weight": 1.5,
    "dimensions": "65 x 35 x 25",
    "price": 160,
    "carryOnLegal": "No",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Kelty",
    "openingStyle": "Top-loading"
  },
  {
    "id": "asher-65",
    "name": "Asher 65",
    "brand": "Kelty",
    "model": "Asher 65",
    "volume": 65,
    "weight": 1.7,
    "dimensions": "70 x 35 x 25",
    "price": 180,
    "carryOnLegal": "No",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Kelty",
    "openingStyle": "Top-loading"
  },
  {
    "id": "redwing-32",
    "name": "Redwing 32",
    "brand": "Kelty",
    "model": "Redwing 32",
    "volume": 32,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 110,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "redwing-44",
    "name": "Redwing 44",
    "brand": "Kelty",
    "model": "Redwing 44",
    "volume": 44,
    "weight": 1.4,
    "dimensions": "55 x 35 x 23",
    "price": 130,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "daypack",
    "name": "Daypack",
    "brand": "Lems",
    "model": "Daypack",
    "volume": 20,
    "weight": 0.6,
    "dimensions": "45 x 28 x 15",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Lems",
    "openingStyle": "Top-loading"
  },
  {
    "id": "travel-pack",
    "name": "Travel Pack",
    "brand": "Lems",
    "model": "Travel Pack",
    "volume": 30,
    "weight": 0.9,
    "dimensions": "50 x 30 x 20",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Lems",
    "openingStyle": "Top-loading"
  },
  {
    "id": "alpine-airzone-pro-30",
    "name": "Alpine AirZone Pro 30",
    "brand": "Lowe",
    "model": "Alpine AirZone Pro 30",
    "volume": 30,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 130,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Lowe Alpine",
    "openingStyle": "Top-loading"
  },
  {
    "id": "alpine-airzone-trail-35",
    "name": "Alpine AirZone Trail 35",
    "brand": "Lowe",
    "model": "Alpine AirZone Trail 35",
    "volume": 35,
    "weight": 1.3,
    "dimensions": "55 x 35 x 20",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Lowe Alpine",
    "openingStyle": "Top-loading"
  },
  {
    "id": "seon-courier",
    "name": "Seon Courier",
    "brand": "Mammut",
    "model": "Seon Courier",
    "volume": 30,
    "weight": 1,
    "dimensions": "50 x 30 x 20",
    "price": 140,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Mammut",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "xeron-flip-22",
    "name": "Xeron Flip 22",
    "brand": "Mammut",
    "model": "Xeron Flip 22",
    "volume": 22,
    "weight": 0.7,
    "dimensions": "46 x 28 x 16",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Mammut",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "beast28",
    "name": "Beast28",
    "brand": "Matador",
    "model": "Beast28",
    "volume": 28,
    "weight": 0.7,
    "dimensions": "48 x 30 x 18",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "beast28-technical-pack",
    "name": "Beast28 Technical Pack",
    "brand": "Matador",
    "model": "Beast28 Technical Pack",
    "volume": 28,
    "weight": 0.85,
    "dimensions": "48 x 30 x 18",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Matador",
    "openingStyle": "Top-loading"
  },
  {
    "id": "freerain-24",
    "name": "Freerain 24",
    "brand": "Matador",
    "model": "Freerain 24",
    "volume": 24,
    "weight": 0.4,
    "dimensions": "45 x 28 x 15",
    "price": 90,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "freerain-32",
    "name": "Freerain 32",
    "brand": "Matador",
    "model": "Freerain 32",
    "volume": 32,
    "weight": 0.5,
    "dimensions": "50 x 30 x 20",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "seg28",
    "name": "SEG28",
    "brand": "Matador",
    "model": "SEG28",
    "volume": 28,
    "weight": 0.6,
    "dimensions": "48 x 30 x 18",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "seg42-travel-pack",
    "name": "SEG42 Travel Pack",
    "brand": "Matador",
    "model": "SEG42 Travel Pack",
    "volume": 42,
    "weight": 1.3,
    "dimensions": "55 x 35 x 22",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Matador",
    "openingStyle": "Segmented"
  },
  {
    "id": "seg45",
    "name": "SEG45",
    "brand": "Matador",
    "model": "SEG45",
    "volume": 45,
    "weight": 0.8,
    "dimensions": "55 x 35 x 23",
    "price": 200,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "fraser-rucksack-32l",
    "name": "Fraser Rucksack 32L",
    "brand": "Millican",
    "model": "Fraser Rucksack 32L",
    "volume": 32,
    "weight": 1.2,
    "dimensions": "52 x 32 x 20",
    "price": 190,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Millican",
    "openingStyle": "Top-loading"
  },
  {
    "id": "smith-roll-pack-25l",
    "name": "Smith Roll Pack 25L",
    "brand": "Millican",
    "model": "Smith Roll Pack 25L",
    "volume": 25,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 170,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Millican",
    "openingStyle": "Roll-top"
  },
  {
    "id": "carry-on-2-0",
    "name": "Carry-on 2.0",
    "brand": "Minaal",
    "model": "Carry-on 2.0",
    "volume": 35,
    "weight": 1.5,
    "dimensions": "55 x 35 x 20",
    "price": 279,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Clamshell"
  },
  {
    "id": "daily-2-0",
    "name": "Daily 2.0",
    "brand": "Minaal",
    "model": "Daily 2.0",
    "volume": 20,
    "weight": 0.8,
    "dimensions": "45 x 28 x 15",
    "price": 179,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Clamshell"
  },
  {
    "id": "workshop-fitzroy",
    "name": "Workshop Fitzroy",
    "brand": "Mission",
    "model": "Workshop Fitzroy",
    "volume": 22,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "workshop-rhake",
    "name": "Workshop Rhake",
    "brand": "Mission",
    "model": "Workshop Rhake",
    "volume": 22,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 400,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Mission Workshop",
    "openingStyle": "Roll-top"
  },
  {
    "id": "workshop-vandal",
    "name": "Workshop Vandal",
    "brand": "Mission",
    "model": "Workshop Vandal",
    "volume": 40,
    "weight": 1.4,
    "dimensions": "55 x 35 x 20",
    "price": 350,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "hardwear-camp-4-40",
    "name": "Hardwear Camp 4 40",
    "brand": "Mountain",
    "model": "Hardwear Camp 4 40",
    "volume": 40,
    "weight": 1.2,
    "dimensions": "55 x 35 x 20",
    "price": 160,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Mountain Hardwear",
    "openingStyle": "Top-loading"
  },
  {
    "id": "hardwear-scrambler-30",
    "name": "Hardwear Scrambler 30",
    "brand": "Mountain",
    "model": "Hardwear Scrambler 30",
    "volume": 30,
    "weight": 0.9,
    "dimensions": "50 x 30 x 20",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "hardwear-scrambler-35",
    "name": "Hardwear Scrambler 35",
    "brand": "Mountain",
    "model": "Hardwear Scrambler 35",
    "volume": 35,
    "weight": 1,
    "dimensions": "53 x 33 x 20",
    "price": 170,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "approach-25",
    "name": "Approach 25",
    "brand": "Mountainsmith",
    "model": "Approach 25",
    "volume": 25,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Mountainsmith",
    "openingStyle": "Top-loading"
  },
  {
    "id": "approach-35",
    "name": "Approach 35",
    "brand": "Mountainsmith",
    "model": "Approach 35",
    "volume": 35,
    "weight": 1.2,
    "dimensions": "55 x 35 x 20",
    "price": 140,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Mountainsmith",
    "openingStyle": "Top-loading"
  },
  {
    "id": "ranch-2-day-assault",
    "name": "Ranch 2 Day Assault",
    "brand": "Mystery",
    "model": "Ranch 2 Day Assault",
    "volume": 27,
    "weight": 1.1,
    "dimensions": "48 x 30 x 18",
    "price": 199,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "ranch-urban-assault-18",
    "name": "Ranch Urban Assault 18",
    "brand": "Mystery",
    "model": "Ranch Urban Assault 18",
    "volume": 18,
    "weight": 0.8,
    "dimensions": "43 x 25 x 15",
    "price": 119,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "ranch-urban-assault-21",
    "name": "Ranch Urban Assault 21",
    "brand": "Mystery",
    "model": "Ranch Urban Assault 21",
    "volume": 21,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 129,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "ranch-urban-assault-24",
    "name": "Ranch Urban Assault 24",
    "brand": "Mystery",
    "model": "Ranch Urban Assault 24",
    "volume": 24,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 139,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "lane-bento-bag",
    "name": "Lane Bento Bag",
    "brand": "Nomad",
    "model": "Lane Bento Bag",
    "volume": 30,
    "weight": 1.3,
    "dimensions": "50 x 30 x 20",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Nomad Lane",
    "openingStyle": "Clamshell"
  },
  {
    "id": "lane-bento-bag-pro",
    "name": "Lane Bento Bag Pro",
    "brand": "Nomad",
    "model": "Lane Bento Bag Pro",
    "volume": 35,
    "weight": 1.5,
    "dimensions": "55 x 35 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Nomad Lane",
    "openingStyle": "Clamshell"
  },
  {
    "id": "backpack-20l",
    "name": "Backpack 20L",
    "brand": "Nomatic",
    "model": "Backpack 20L",
    "volume": 20,
    "weight": 1.1,
    "dimensions": "45 x 28 x 15",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Nomatic",
    "openingStyle": "Clamshell"
  },
  {
    "id": "travel-pack-40l",
    "name": "Travel Pack 40L",
    "brand": "Nomatic",
    "model": "Travel Pack 40L",
    "volume": 40,
    "weight": 1.8,
    "dimensions": "55 x 35 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Nomatic",
    "openingStyle": "Clamshell"
  },
  {
    "id": "commuter-daypack-city",
    "name": "Commuter Daypack City",
    "brand": "Ortlieb",
    "model": "Commuter Daypack City",
    "volume": 21,
    "weight": 0.8,
    "dimensions": "45 x 28 x 15",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Ortlieb",
    "openingStyle": "Roll-top"
  },
  {
    "id": "velocity",
    "name": "Velocity",
    "brand": "Ortlieb",
    "model": "Velocity",
    "volume": 23,
    "weight": 1,
    "dimensions": "47 x 28 x 15",
    "price": 160,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "No",
    "source": "Ortlieb",
    "openingStyle": "Roll-top"
  },
  {
    "id": "daylite-26-6",
    "name": "Daylite 26+6",
    "brand": "Osprey",
    "model": "Daylite 26+6",
    "volume": 32,
    "weight": 0.7,
    "dimensions": "48 x 28 x 20",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "daylite-plus",
    "name": "Daylite Plus",
    "brand": "Osprey",
    "model": "Daylite Plus",
    "volume": 20,
    "weight": 0.5,
    "dimensions": "43 x 25 x 15",
    "price": 80,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "daylite-plus-20l",
    "name": "Daylite Plus 20L",
    "brand": "Osprey",
    "model": "Daylite Plus 20L",
    "volume": 20,
    "weight": 0.5,
    "dimensions": "43 x 25 x 15",
    "price": 80,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "farpoint-40",
    "name": "Farpoint 40",
    "brand": "Osprey",
    "model": "Farpoint 40",
    "volume": 40,
    "weight": 1.44,
    "dimensions": "55 x 35 x 23",
    "price": 160,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "farpoint-55",
    "name": "Farpoint 55",
    "brand": "Osprey",
    "model": "Farpoint 55",
    "volume": 55,
    "weight": 1.7,
    "dimensions": "60 x 35 x 25",
    "price": 200,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "farpoint-55l",
    "name": "Farpoint 55L",
    "brand": "Osprey",
    "model": "Farpoint 55L",
    "volume": 55,
    "weight": 1.7,
    "dimensions": "60 x 35 x 25",
    "price": 200,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "porter-30",
    "name": "Porter 30",
    "brand": "Osprey",
    "model": "Porter 30",
    "volume": 30,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "porter-30l",
    "name": "Porter 30L",
    "brand": "Osprey",
    "model": "Porter 30L",
    "volume": 30,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "porter-46",
    "name": "Porter 46",
    "brand": "Osprey",
    "model": "Porter 46",
    "volume": 46,
    "weight": 1.5,
    "dimensions": "56 x 35 x 23",
    "price": 140,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "black-hole-25l",
    "name": "Black Hole 25L",
    "brand": "Patagonia",
    "model": "Black Hole 25L",
    "volume": 25,
    "weight": 0.7,
    "dimensions": "48 x 28 x 18",
    "price": 119,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "black-hole-32l",
    "name": "Black Hole 32L",
    "brand": "Patagonia",
    "model": "Black Hole 32L",
    "volume": 32,
    "weight": 0.9,
    "dimensions": "50 x 30 x 20",
    "price": 159,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Patagonia",
    "openingStyle": "Top-loading"
  },
  {
    "id": "black-hole-40l",
    "name": "Black Hole 40L",
    "brand": "Patagonia",
    "model": "Black Hole 40L",
    "volume": 40,
    "weight": 0.9,
    "dimensions": "53 x 33 x 20",
    "price": 149,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "refugio-26l",
    "name": "Refugio 26L",
    "brand": "Patagonia",
    "model": "Refugio 26L",
    "volume": 26,
    "weight": 0.8,
    "dimensions": "48 x 30 x 18",
    "price": 129,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Patagonia",
    "openingStyle": "Top-loading"
  },
  {
    "id": "design-everyday-backpack-20l",
    "name": "Design Everyday Backpack 20L",
    "brand": "Peak",
    "model": "Design Everyday Backpack 20L",
    "volume": 20,
    "weight": 1.1,
    "dimensions": "45 x 28 x 15",
    "price": 230,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "design-everyday-backpack-30l",
    "name": "Design Everyday Backpack 30L",
    "brand": "Peak",
    "model": "Design Everyday Backpack 30L",
    "volume": 30,
    "weight": 1.3,
    "dimensions": "48 x 30 x 18",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "design-everyday-backpack-zip-15l",
    "name": "Design Everyday Backpack Zip 15L",
    "brand": "Peak",
    "model": "Design Everyday Backpack Zip 15L",
    "volume": 15,
    "weight": 0.9,
    "dimensions": "40 x 25 x 13",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Peak Design",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "design-everyday-backpack-zip-20l",
    "name": "Design Everyday Backpack Zip 20L",
    "brand": "Peak",
    "model": "Design Everyday Backpack Zip 20L",
    "volume": 20,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Peak Design",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "design-everyday-sling-3l",
    "name": "Design Everyday Sling 3L",
    "brand": "Peak",
    "model": "Design Everyday Sling 3L",
    "volume": 3,
    "weight": 0.3,
    "dimensions": "30 x 20 x 10",
    "price": 80,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "No",
    "source": "Peak Design",
    "openingStyle": "Sling"
  },
  {
    "id": "design-everyday-sling-6l",
    "name": "Design Everyday Sling 6L",
    "brand": "Peak",
    "model": "Design Everyday Sling 6L",
    "volume": 6,
    "weight": 0.4,
    "dimensions": "35 x 22 x 12",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "No",
    "source": "Peak Design",
    "openingStyle": "Sling"
  },
  {
    "id": "design-travel-backpack-30l",
    "name": "Design Travel Backpack 30L",
    "brand": "Peak",
    "model": "Design Travel Backpack 30L",
    "volume": 30,
    "weight": 1.5,
    "dimensions": "50 x 30 x 20",
    "price": 280,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Clamshell"
  },
  {
    "id": "design-travel-backpack-45l",
    "name": "Design Travel Backpack 45L",
    "brand": "Peak",
    "model": "Design Travel Backpack 45L",
    "volume": 45,
    "weight": 2.05,
    "dimensions": "55 x 35 x 23",
    "price": 300,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Clamshell"
  },
  {
    "id": "design-travel-backpack-65l",
    "name": "Design Travel Backpack 65L",
    "brand": "Peak",
    "model": "Design Travel Backpack 65L",
    "volume": 65,
    "weight": 2.2,
    "dimensions": "65 x 35 x 25",
    "price": 350,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Peak Design",
    "openingStyle": "Clamshell"
  },
  {
    "id": "design-travel-duffel-35l",
    "name": "Design Travel Duffel 35L",
    "brand": "Peak",
    "model": "Design Travel Duffel 35L",
    "volume": 35,
    "weight": 1.3,
    "dimensions": "55 x 30 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Peak Design",
    "openingStyle": "Duffel"
  },
  {
    "id": "design-travel-duffel-65l",
    "name": "Design Travel Duffel 65L",
    "brand": "Peak",
    "model": "Design Travel Duffel 65L",
    "volume": 65,
    "weight": 1.8,
    "dimensions": "65 x 35 x 25",
    "price": 250,
    "carryOnLegal": "No",
    "laptopCompartment": "No",
    "waterBottleCompartment": "Yes",
    "source": "Peak Design",
    "openingStyle": "Duffel"
  },
  {
    "id": "backpack",
    "name": "Backpack",
    "brand": "Rains",
    "model": "Backpack",
    "volume": 25,
    "weight": 0.8,
    "dimensions": "48 x 30 x 18",
    "price": 120,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Rains",
    "openingStyle": "Top-loading"
  },
  {
    "id": "rolltop-backpack",
    "name": "Rolltop Backpack",
    "brand": "Rains",
    "model": "Rolltop Backpack",
    "volume": 20,
    "weight": 0.7,
    "dimensions": "45 x 28 x 15",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Rains",
    "openingStyle": "Roll-top"
  },
  {
    "id": "firefighter-24-hour",
    "name": "Firefighter 24 Hour",
    "brand": "Recycled",
    "model": "Firefighter 24 Hour",
    "volume": 24,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "oxx-air-boss",
    "name": "Oxx Air Boss",
    "brand": "Red",
    "model": "Oxx Air Boss",
    "volume": 35,
    "weight": 1.5,
    "dimensions": "55 x 35 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Red Oxx",
    "openingStyle": "Clamshell"
  },
  {
    "id": "oxx-c-ruck",
    "name": "Oxx C-Ruck",
    "brand": "Red",
    "model": "Oxx C-Ruck",
    "volume": 35,
    "weight": 1.4,
    "dimensions": "55 x 35 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Red Oxx",
    "openingStyle": "Top-loading"
  },
  {
    "id": "oxx-metro",
    "name": "Oxx Metro",
    "brand": "Red",
    "model": "Oxx Metro",
    "volume": 20,
    "weight": 0.9,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Red Oxx",
    "openingStyle": "Top-loading"
  },
  {
    "id": "oxx-metro-backpack",
    "name": "Oxx Metro Backpack",
    "brand": "Red",
    "model": "Oxx Metro Backpack",
    "volume": 25,
    "weight": 1.2,
    "dimensions": "48 x 30 x 18",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Red Oxx",
    "openingStyle": "Top-loading"
  },
  {
    "id": "flash-22",
    "name": "Flash 22",
    "brand": "REI",
    "model": "Flash 22",
    "volume": 22,
    "weight": 0.7,
    "dimensions": "45 x 28 x 15",
    "price": 69,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "ruckpack-28",
    "name": "Ruckpack 28",
    "brand": "REI",
    "model": "Ruckpack 28",
    "volume": 28,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 99,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "trail-25",
    "name": "Trail 25",
    "brand": "REI",
    "model": "Trail 25",
    "volume": 25,
    "weight": 0.9,
    "dimensions": "48 x 30 x 18",
    "price": 89,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "trail-40",
    "name": "Trail 40",
    "brand": "REI",
    "model": "Trail 40",
    "volume": 40,
    "weight": 1.2,
    "dimensions": "55 x 35 x 20",
    "price": 119,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "equipment-alpha-31",
    "name": "Equipment Alpha 31",
    "brand": "Remote",
    "model": "Equipment Alpha 31",
    "volume": 31,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "tectonic-2",
    "name": "Tectonic 2",
    "brand": "Samsonite",
    "model": "Tectonic 2",
    "volume": 35,
    "weight": 1.4,
    "dimensions": "55 x 35 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Samsonite",
    "openingStyle": "Clamshell"
  },
  {
    "id": "xenon-3-0",
    "name": "Xenon 3.0",
    "brand": "Samsonite",
    "model": "Xenon 3.0",
    "volume": 30,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Samsonite",
    "openingStyle": "Clamshell"
  },
  {
    "id": "bernt",
    "name": "Bernt",
    "brand": "Sandqvist",
    "model": "Bernt",
    "volume": 20,
    "weight": 0.7,
    "dimensions": "45 x 28 x 15",
    "price": 140,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Sandqvist",
    "openingStyle": "Roll-top"
  },
  {
    "id": "zack",
    "name": "Zack",
    "brand": "Sandqvist",
    "model": "Zack",
    "volume": 26,
    "weight": 0.9,
    "dimensions": "47 x 29 x 17",
    "price": 160,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Sandqvist",
    "openingStyle": "Top-loading"
  },
  {
    "id": "action-x30",
    "name": "Action X30",
    "brand": "Shimoda",
    "model": "Action X30",
    "volume": 30,
    "weight": 1.5,
    "dimensions": "50 x 30 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "action-x30-v2",
    "name": "Action X30 V2",
    "brand": "Shimoda",
    "model": "Action X30 V2",
    "volume": 30,
    "weight": 1.4,
    "dimensions": "50 x 30 x 20",
    "price": 320,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "action-x50",
    "name": "Action X50",
    "brand": "Shimoda",
    "model": "Action X50",
    "volume": 50,
    "weight": 2,
    "dimensions": "60 x 35 x 25",
    "price": 350,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "action-x50-v2",
    "name": "Action X50 V2",
    "brand": "Shimoda",
    "model": "Action X50 V2",
    "volume": 50,
    "weight": 1.9,
    "dimensions": "60 x 35 x 25",
    "price": 360,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "action-x70",
    "name": "Action X70",
    "brand": "Shimoda",
    "model": "Action X70",
    "volume": 70,
    "weight": 2.4,
    "dimensions": "65 x 35 x 25",
    "price": 380,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "action-x70-v2",
    "name": "Action X70 V2",
    "brand": "Shimoda",
    "model": "Action X70 V2",
    "volume": 70,
    "weight": 2.3,
    "dimensions": "65 x 35 x 25",
    "price": 390,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "explore-v2-25l",
    "name": "Explore V2 25L",
    "brand": "Shimoda",
    "model": "Explore V2 25L",
    "volume": 25,
    "weight": 1.4,
    "dimensions": "48 x 30 x 18",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "explore-v2-30l",
    "name": "Explore V2 30L",
    "brand": "Shimoda",
    "model": "Explore V2 30L",
    "volume": 30,
    "weight": 1.6,
    "dimensions": "50 x 30 x 20",
    "price": 320,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "explore-v2-35l",
    "name": "Explore V2 35L",
    "brand": "Shimoda",
    "model": "Explore V2 35L",
    "volume": 35,
    "weight": 1.8,
    "dimensions": "55 x 35 x 20",
    "price": 340,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Shimoda",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "north-face-base-camp-voyager-32l",
    "name": "North Face Base Camp Voyager 32L",
    "brand": "The",
    "model": "North Face Base Camp Voyager 32L",
    "volume": 32,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 129,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "north-face-borealis",
    "name": "North Face Borealis",
    "brand": "The",
    "model": "North Face Borealis",
    "volume": 28,
    "weight": 0.8,
    "dimensions": "48 x 30 x 18",
    "price": 89,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "north-face-recon",
    "name": "North Face Recon",
    "brand": "The",
    "model": "North Face Recon",
    "volume": 30,
    "weight": 0.9,
    "dimensions": "48 x 30 x 18",
    "price": 99,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "crossover-32l",
    "name": "Crossover 32L",
    "brand": "Thule",
    "model": "Crossover 32L",
    "volume": 32,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 170,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "landmark-40l",
    "name": "Landmark 40L",
    "brand": "Thule",
    "model": "Landmark 40L",
    "volume": 40,
    "weight": 1.3,
    "dimensions": "55 x 35 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "subterra-34l",
    "name": "Subterra 34L",
    "brand": "Thule",
    "model": "Subterra 34L",
    "volume": 34,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "division",
    "name": "Division",
    "brand": "Timbuk2",
    "model": "Division",
    "volume": 24,
    "weight": 0.8,
    "dimensions": "45 x 28 x 15",
    "price": 150,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "never-check",
    "name": "Never Check",
    "brand": "Timbuk2",
    "model": "Never Check",
    "volume": 40,
    "weight": 1.3,
    "dimensions": "55 x 35 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "bihn-aeronaut-45",
    "name": "Bihn Aeronaut 45",
    "brand": "Tom",
    "model": "Bihn Aeronaut 45",
    "volume": 45,
    "weight": 1.6,
    "dimensions": "55 x 35 x 23",
    "price": 330,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "bihn-synapse-25",
    "name": "Bihn Synapse 25",
    "brand": "Tom",
    "model": "Bihn Synapse 25",
    "volume": 25,
    "weight": 1.1,
    "dimensions": "45 x 28 x 15",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Tom Bihn",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "bihn-synik-22",
    "name": "Bihn Synik 22",
    "brand": "Tom",
    "model": "Bihn Synik 22",
    "volume": 22,
    "weight": 1.1,
    "dimensions": "45 x 28 x 15",
    "price": 280,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "bihn-synik-30",
    "name": "Bihn Synik 30",
    "brand": "Tom",
    "model": "Bihn Synik 30",
    "volume": 30,
    "weight": 1.3,
    "dimensions": "50 x 30 x 20",
    "price": 300,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Tom Bihn",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "bihn-techonaut-30",
    "name": "Bihn Techonaut 30",
    "brand": "Tom",
    "model": "Bihn Techonaut 30",
    "volume": 30,
    "weight": 1.4,
    "dimensions": "48 x 30 x 18",
    "price": 320,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "designs-core-pack",
    "name": "Designs Core Pack",
    "brand": "Topo",
    "model": "Designs Core Pack",
    "volume": 25,
    "weight": 1,
    "dimensions": "48 x 30 x 18",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Topo Designs",
    "openingStyle": "Top-loading"
  },
  {
    "id": "designs-global-travel-bag-30l",
    "name": "Designs Global Travel Bag 30L",
    "brand": "Topo",
    "model": "Designs Global Travel Bag 30L",
    "volume": 30,
    "weight": 1.2,
    "dimensions": "50 x 30 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Topo Designs",
    "openingStyle": "Clamshell"
  },
  {
    "id": "outbreaker-35l",
    "name": "Outbreaker 35L",
    "brand": "Tortuga",
    "model": "Outbreaker 35L",
    "volume": 35,
    "weight": 1.7,
    "dimensions": "53 x 33 x 20",
    "price": 299,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "setout-45l",
    "name": "Setout 45L",
    "brand": "Tortuga",
    "model": "Setout 45L",
    "volume": 45,
    "weight": 1.9,
    "dimensions": "55 x 35 x 23",
    "price": 229,
    "carryOnLegal": "Yes (some airlines)",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "setout-divide",
    "name": "Setout Divide",
    "brand": "Tortuga",
    "model": "Setout Divide",
    "volume": "26-34",
    "weight": 1.4,
    "dimensions": "50 x 30 x 20",
    "price": 199,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "travel-backpack-40l",
    "name": "Travel Backpack 40L",
    "brand": "Tortuga",
    "model": "Travel Backpack 40L",
    "volume": 40,
    "weight": 1.8,
    "dimensions": "55 x 35 x 20",
    "price": 249,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Clamshell"
  },
  {
    "id": "nest",
    "name": "Nest",
    "brand": "Tropicfeel",
    "model": "Nest",
    "volume": 25,
    "weight": 0.9,
    "dimensions": "48 x 30 x 18",
    "price": 180,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Tropicfeel",
    "openingStyle": "Clamshell"
  },
  {
    "id": "shell",
    "name": "Shell",
    "brand": "Tropicfeel",
    "model": "Shell",
    "volume": 30,
    "weight": 1.1,
    "dimensions": "50 x 30 x 20",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Tropicfeel",
    "openingStyle": "Clamshell"
  },
  {
    "id": "alpha-bravo-search",
    "name": "Alpha Bravo Search",
    "brand": "Tumi",
    "model": "Alpha Bravo Search",
    "volume": 30,
    "weight": 1.5,
    "dimensions": "50 x 30 x 20",
    "price": 400,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Tumi",
    "openingStyle": "Clamshell"
  },
  {
    "id": "voyageur-calais",
    "name": "Voyageur Calais",
    "brand": "Tumi",
    "model": "Voyageur Calais",
    "volume": 25,
    "weight": 1.2,
    "dimensions": "48 x 30 x 18",
    "price": 350,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Tumi",
    "openingStyle": "Clamshell"
  },
  {
    "id": "atlas",
    "name": "Atlas",
    "brand": "ULA",
    "model": "Atlas",
    "volume": 50,
    "weight": 1.1,
    "dimensions": "60 x 35 x 25",
    "price": 250,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Amazon",
    "openingStyle": "Top-loading"
  },
  {
    "id": "circuit",
    "name": "Circuit",
    "brand": "ULA",
    "model": "Circuit",
    "volume": 68,
    "weight": 1.3,
    "dimensions": "65 x 35 x 25",
    "price": 300,
    "carryOnLegal": "No",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Reddit",
    "openingStyle": "Top-loading"
  },
  {
    "id": "dragonfly-ultra",
    "name": "Dragonfly Ultra",
    "brand": "ULA",
    "model": "Dragonfly Ultra",
    "volume": 30,
    "weight": 0.8,
    "dimensions": "48 x 30 x 18",
    "price": 220,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "REI",
    "openingStyle": "Top-loading"
  },
  {
    "id": "citygo-23",
    "name": "Citygo 23",
    "brand": "Vaude",
    "model": "Citygo 23",
    "volume": 23,
    "weight": 0.8,
    "dimensions": "46 x 28 x 16",
    "price": 100,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Vaude",
    "openingStyle": "Panel-loading"
  },
  {
    "id": "wizard-30-4",
    "name": "Wizard 30+4",
    "brand": "Vaude",
    "model": "Wizard 30+4",
    "volume": 34,
    "weight": 1.2,
    "dimensions": "52 x 32 x 20",
    "price": 130,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Vaude",
    "openingStyle": "Top-loading"
  },
  {
    "id": "duo-daypack",
    "name": "Duo Daypack",
    "brand": "Wandrd",
    "model": "Duo Daypack",
    "volume": 20,
    "weight": 1,
    "dimensions": "45 x 28 x 15",
    "price": 200,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Wandrd",
    "openingStyle": "Roll-top"
  },
  {
    "id": "prvke-31l",
    "name": "PRVKE 31L",
    "brand": "Wandrd",
    "model": "PRVKE 31L",
    "volume": 31,
    "weight": 1.5,
    "dimensions": "50 x 30 x 20",
    "price": 250,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "Wandrd",
    "openingStyle": "Roll-top"
  },
  {
    "id": "rofmia-backpack-v2",
    "name": "Backpack V2",
    "brand": "ROFMIA",
    "model": "Backpack V2",
    "volume": 40,
    "weight": 0.895,
    "dimensions": "48 x 30 x 16",
    "price": 650,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "ROFMIA",
    "openingStyle": "Roll-top"
  },
  {
    "id": "rofmia-daypack-v2",
    "name": "Daypack V2",
    "brand": "ROFMIA",
    "model": "Daypack V2",
    "volume": 28,
    "weight": 0.795,
    "dimensions": "45 x 28 x 15",
    "price": 580,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes",
    "waterBottleCompartment": "Yes",
    "source": "ROFMIA",
    "openingStyle": "Roll-top"
  },
  {
    "id": "evergoods-ctb35",
    "name": "CIVIC Travel Bag 35L",
    "brand": "Evergoods",
    "model": "CIVIC Travel Bag 35L",
    "volume": 35,
    "weight": 1.8,
    "dimensions": "52 x 30.5 x 24",
    "price": 349,
    "carryOnLegal": "Yes",
    "laptopCompartment": "Yes (17\")",
    "waterBottleCompartment": "Yes",
    "source": "Evergoods",
    "openingStyle": "Clamshell"
  }
];
